name = "ocs-websocket-worker"
main = "index.js"
compatibility_date = "2025-04-11"

# Enable Node.js compatibility for assert imports
compatibility_flags = ["nodejs_compat"]

# Bundle additional files
[build]
include = ["function_schemas.json", "prompt.md"]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
head_sampling_rate = 1

[env.production.vars]
DEEPSEEK_API_KEY = "sk-c1025eafaea049909360bb3ef9add2a9"
SQL_API_BASE_URL = "https://restless-tree-1740.ptson117.workers.dev"

[[env.production.services]]
binding = "OCS_BACKEND"
service = "restless-tree-1740"
environment = "production"